/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThingsINoticeRouteImport } from './routes/things-i-notice'
import { Route as TheGirlISawRouteImport } from './routes/the-girl-i-saw'
import { Route as ParallelUniversesRouteImport } from './routes/parallel-universes'
import { Route as OverthinksRouteImport } from './routes/overthinks'
import { Route as MusicRouteImport } from './routes/music'
import { Route as LettersUnsentRouteImport } from './routes/letters-unsent'
import { Route as HerWorldRouteImport } from './routes/her-world'
import { Route as EndingRouteImport } from './routes/ending'
import { Route as IndexRouteImport } from './routes/index'

const ThingsINoticeRoute = ThingsINoticeRouteImport.update({
  id: '/things-i-notice',
  path: '/things-i-notice',
  getParentRoute: () => rootRouteImport,
} as any)
const TheGirlISawRoute = TheGirlISawRouteImport.update({
  id: '/the-girl-i-saw',
  path: '/the-girl-i-saw',
  getParentRoute: () => rootRouteImport,
} as any)
const ParallelUniversesRoute = ParallelUniversesRouteImport.update({
  id: '/parallel-universes',
  path: '/parallel-universes',
  getParentRoute: () => rootRouteImport,
} as any)
const OverthinksRoute = OverthinksRouteImport.update({
  id: '/overthinks',
  path: '/overthinks',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicRoute = MusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => rootRouteImport,
} as any)
const LettersUnsentRoute = LettersUnsentRouteImport.update({
  id: '/letters-unsent',
  path: '/letters-unsent',
  getParentRoute: () => rootRouteImport,
} as any)
const HerWorldRoute = HerWorldRouteImport.update({
  id: '/her-world',
  path: '/her-world',
  getParentRoute: () => rootRouteImport,
} as any)
const EndingRoute = EndingRouteImport.update({
  id: '/ending',
  path: '/ending',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ending': typeof EndingRoute
  '/her-world': typeof HerWorldRoute
  '/letters-unsent': typeof LettersUnsentRoute
  '/music': typeof MusicRoute
  '/overthinks': typeof OverthinksRoute
  '/parallel-universes': typeof ParallelUniversesRoute
  '/the-girl-i-saw': typeof TheGirlISawRoute
  '/things-i-notice': typeof ThingsINoticeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ending': typeof EndingRoute
  '/her-world': typeof HerWorldRoute
  '/letters-unsent': typeof LettersUnsentRoute
  '/music': typeof MusicRoute
  '/overthinks': typeof OverthinksRoute
  '/parallel-universes': typeof ParallelUniversesRoute
  '/the-girl-i-saw': typeof TheGirlISawRoute
  '/things-i-notice': typeof ThingsINoticeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ending': typeof EndingRoute
  '/her-world': typeof HerWorldRoute
  '/letters-unsent': typeof LettersUnsentRoute
  '/music': typeof MusicRoute
  '/overthinks': typeof OverthinksRoute
  '/parallel-universes': typeof ParallelUniversesRoute
  '/the-girl-i-saw': typeof TheGirlISawRoute
  '/things-i-notice': typeof ThingsINoticeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ending'
    | '/her-world'
    | '/letters-unsent'
    | '/music'
    | '/overthinks'
    | '/parallel-universes'
    | '/the-girl-i-saw'
    | '/things-i-notice'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ending'
    | '/her-world'
    | '/letters-unsent'
    | '/music'
    | '/overthinks'
    | '/parallel-universes'
    | '/the-girl-i-saw'
    | '/things-i-notice'
  id:
    | '__root__'
    | '/'
    | '/ending'
    | '/her-world'
    | '/letters-unsent'
    | '/music'
    | '/overthinks'
    | '/parallel-universes'
    | '/the-girl-i-saw'
    | '/things-i-notice'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EndingRoute: typeof EndingRoute
  HerWorldRoute: typeof HerWorldRoute
  LettersUnsentRoute: typeof LettersUnsentRoute
  MusicRoute: typeof MusicRoute
  OverthinksRoute: typeof OverthinksRoute
  ParallelUniversesRoute: typeof ParallelUniversesRoute
  TheGirlISawRoute: typeof TheGirlISawRoute
  ThingsINoticeRoute: typeof ThingsINoticeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/things-i-notice': {
      id: '/things-i-notice'
      path: '/things-i-notice'
      fullPath: '/things-i-notice'
      preLoaderRoute: typeof ThingsINoticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/the-girl-i-saw': {
      id: '/the-girl-i-saw'
      path: '/the-girl-i-saw'
      fullPath: '/the-girl-i-saw'
      preLoaderRoute: typeof TheGirlISawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parallel-universes': {
      id: '/parallel-universes'
      path: '/parallel-universes'
      fullPath: '/parallel-universes'
      preLoaderRoute: typeof ParallelUniversesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overthinks': {
      id: '/overthinks'
      path: '/overthinks'
      fullPath: '/overthinks'
      preLoaderRoute: typeof OverthinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music': {
      id: '/music'
      path: '/music'
      fullPath: '/music'
      preLoaderRoute: typeof MusicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/letters-unsent': {
      id: '/letters-unsent'
      path: '/letters-unsent'
      fullPath: '/letters-unsent'
      preLoaderRoute: typeof LettersUnsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/her-world': {
      id: '/her-world'
      path: '/her-world'
      fullPath: '/her-world'
      preLoaderRoute: typeof HerWorldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ending': {
      id: '/ending'
      path: '/ending'
      fullPath: '/ending'
      preLoaderRoute: typeof EndingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EndingRoute: EndingRoute,
  HerWorldRoute: HerWorldRoute,
  LettersUnsentRoute: LettersUnsentRoute,
  MusicRoute: MusicRoute,
  OverthinksRoute: OverthinksRoute,
  ParallelUniversesRoute: ParallelUniversesRoute,
  TheGirlISawRoute: TheGirlISawRoute,
  ThingsINoticeRoute: ThingsINoticeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
